### ISSUE TITLE
Pandas logical operator

### ISSUE THREAD

**Issue by ILogre** [jdfekete/progressivis#1]
Hello,
I encounter an issue when trying to execute test (test_csv.py) or a example (nyc_pickup_yellow.py).

> ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

From a quick search I find that it's often related to the use or the _or/and_ operators which should be respectively replaced by _|/&_ when using pandas.
As the example is already doing exactly that, I foresee to possibilities : either there is a _or/and_ somewhere in the core, or it as to do with the if/while operator which could lead to the very same error.

It is my first try at executing something in ProgressiVis, did I installed or set up something wrong ?

Thank you !

The full trace :

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/module.py", line 625, in run
    run_step_ret = self.run_step(run_number, step_size, remaining_time)
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/io/csv_loader.py", line 113, in run_step
    self._buffer.append(df)
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/buffered_dataframe.py", line 63, in append
    self._base = df.append(self._create_dataframe(create_index(len(df),n),df.columns,df.dtypes))
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/buffered_dataframe.py", line 38, in _create_dataframe
    return pd.DataFrame({}, index=index,columns=columns,dtype=dtype)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 321, in __init__
    dtype = self._validate_dtype(dtype)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 152, in _validate_dtype
    dtype = pandas_dtype(dtype)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/dtypes/common.py", line 1960, in pandas_dtype
    if dtype in [object, np.object_, 'object', 'O']:
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Exception in thread Progressive Scheduler:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/scheduler.py", line 360, in run
    self._run_loop()
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/scheduler.py", line 346, in _run_loop
    module.run(self._run_number)
  File "/usr/local/lib/python2.7/site-packages/progressivis-0.0.4-py2.7.egg/progressivis/core/module.py", line 664, in run
    raise exception
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`

Using Python 2.7.14, pandas 0.21.0

**Comment by jdfekete** [comment]
Hi,
This is due to the handling of the dtype parameter in pandas, it changed after 0.19 and is now a unique type when I am passing a series of dtypes, each for one column. I have fixed that in an internal version I am currently working on. I will see if I can fix only that, but meanwhile, use pandas 0.19.1 or 0.19.2.
